"""add last_updated to tasks

Revision ID: 09c23aac26ec
Revises: 2f3faf8b93bd
Create Date: 2026-03-13 16:47:34.716612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c23aac26ec'
down_revision: Union[str, Sequence[str], None] = '2f3faf8b93bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_updated')
    # ### end Alembic commands ###
