"""add index user_id-is_done-position

Revision ID: 24508fc6cc02
Revises: a7f4c3d9e8b1
Create Date: 2026-05-02 12:50:10.270580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24508fc6cc02'
down_revision: Union[str, Sequence[str], None] = 'a7f4c3d9e8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_user_done_position', 'tasks', ['user_id', 'is_done', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_done_position', table_name='tasks')
    # ### end Alembic commands ###
