"""add email to users' model

Revision ID: 916ed82905e3
Revises: 25d6623fc59d
Create Date: 2026-05-09 14:45:15.583933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916ed82905e3'
down_revision: Union[str, Sequence[str], None] = '25d6623fc59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint("uq_users_email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
